from models.gamification import (
    AchievementCategory,
    AchievementDefinition,
    AchievementTier,
    BadgeDefinition,
    BadgeRarity,
    ChallengeDifficulty,
    ChallengePeriodType,
    ChallengeTemplate,
    GamificationMetric,
)


def _badge(
    key: str,
    name_ko: str,
    icon: str,
    rarity: BadgeRarity,
) -> BadgeDefinition:
    """업적에 일대일로 포함할 배지 정의를 만듭니다."""

    return BadgeDefinition(
        key=key,
        name_ko=name_ko,
        icon=icon,
        rarity=rarity,
    )


ACHIEVEMENT_CATALOG: tuple[AchievementDefinition, ...] = (
    AchievementDefinition(
        key="first_task_completed",
        series_key="tasks_completed",
        name_ko="첫걸음",
        description_ko="학습 과제를 처음으로 완료합니다.",
        category=AchievementCategory.TASK,
        tier=AchievementTier.BRONZE,
        metric=GamificationMetric.COMPLETED_TASKS,
        target_value=1,
        reward_exp=10,
        sort_order=10,
        badge=_badge("first_step", "첫걸음 배지", "👣", BadgeRarity.COMMON),
    ),
    AchievementDefinition(
        key="tasks_completed_10",
        series_key="tasks_completed",
        name_ko="꾸준한 실행가",
        description_ko="서로 다른 학습 과제 10개를 완료합니다.",
        category=AchievementCategory.TASK,
        tier=AchievementTier.SILVER,
        metric=GamificationMetric.COMPLETED_TASKS,
        target_value=10,
        reward_exp=20,
        sort_order=20,
        badge=_badge("steady_ten", "꾸준한 실행가 배지", "📝", BadgeRarity.UNCOMMON),
    ),
    AchievementDefinition(
        key="tasks_completed_50",
        series_key="tasks_completed",
        name_ko="학습 루틴",
        description_ko="서로 다른 학습 과제 50개를 완료합니다.",
        category=AchievementCategory.TASK,
        tier=AchievementTier.GOLD,
        metric=GamificationMetric.COMPLETED_TASKS,
        target_value=50,
        reward_exp=30,
        sort_order=30,
        badge=_badge("study_routine", "학습 루틴 배지", "📚", BadgeRarity.RARE),
    ),
    AchievementDefinition(
        key="tasks_completed_100",
        series_key="tasks_completed",
        name_ko="백 번의 성장",
        description_ko="서로 다른 학습 과제 100개를 완료합니다.",
        category=AchievementCategory.TASK,
        tier=AchievementTier.PLATINUM,
        metric=GamificationMetric.COMPLETED_TASKS,
        target_value=100,
        reward_exp=50,
        sort_order=40,
        badge=_badge("hundred_growth", "백 번의 성장 배지", "🏆", BadgeRarity.EPIC),
    ),
    AchievementDefinition(
        key="streak_3_days",
        series_key="learning_streak",
        name_ko="3일 연속 학습",
        description_ko="최장 연속 학습 기록 3일을 달성합니다.",
        category=AchievementCategory.STREAK,
        tier=AchievementTier.BRONZE,
        metric=GamificationMetric.LONGEST_STREAK,
        target_value=3,
        reward_exp=10,
        sort_order=50,
        badge=_badge("streak_three", "3일 연속 배지", "🔥", BadgeRarity.COMMON),
    ),
    AchievementDefinition(
        key="streak_7_days",
        series_key="learning_streak",
        name_ko="일주일의 불꽃",
        description_ko="최장 연속 학습 기록 7일을 달성합니다.",
        category=AchievementCategory.STREAK,
        tier=AchievementTier.SILVER,
        metric=GamificationMetric.LONGEST_STREAK,
        target_value=7,
        reward_exp=20,
        sort_order=60,
        badge=_badge("streak_week", "일주일의 불꽃 배지", "🔥", BadgeRarity.UNCOMMON),
    ),
    AchievementDefinition(
        key="streak_14_days",
        series_key="learning_streak",
        name_ko="두 주의 집중",
        description_ko="최장 연속 학습 기록 14일을 달성합니다.",
        category=AchievementCategory.STREAK,
        tier=AchievementTier.GOLD,
        metric=GamificationMetric.LONGEST_STREAK,
        target_value=14,
        reward_exp=30,
        sort_order=70,
        badge=_badge("streak_fortnight", "두 주의 집중 배지", "🌟", BadgeRarity.RARE),
    ),
    AchievementDefinition(
        key="streak_30_days",
        series_key="learning_streak",
        name_ko="한 달의 습관",
        description_ko="최장 연속 학습 기록 30일을 달성합니다.",
        category=AchievementCategory.STREAK,
        tier=AchievementTier.PLATINUM,
        metric=GamificationMetric.LONGEST_STREAK,
        target_value=30,
        reward_exp=50,
        sort_order=80,
        badge=_badge("streak_month", "한 달의 습관 배지", "💎", BadgeRarity.EPIC),
    ),
    AchievementDefinition(
        key="first_plan_completed",
        series_key="plans_completed",
        name_ko="계획 완주",
        description_ko="과제가 있는 학습계획 하나를 모두 완료합니다.",
        category=AchievementCategory.PLAN,
        tier=AchievementTier.BRONZE,
        metric=GamificationMetric.COMPLETED_PLANS,
        target_value=1,
        reward_exp=20,
        sort_order=90,
        badge=_badge("plan_finisher", "계획 완주 배지", "🗓️", BadgeRarity.UNCOMMON),
    ),
    AchievementDefinition(
        key="review_tasks_completed_1",
        series_key="review_tasks_completed",
        name_ko="첫 복습",
        description_ko="복습 유형 과제를 처음으로 완료합니다.",
        category=AchievementCategory.REVIEW,
        tier=AchievementTier.BRONZE,
        metric=GamificationMetric.COMPLETED_REVIEW_TASKS,
        target_value=1,
        reward_exp=10,
        sort_order=100,
        badge=_badge("first_review", "첫 복습 배지", "🔁", BadgeRarity.COMMON),
    ),
    AchievementDefinition(
        key="first_quiz_submitted",
        series_key="quiz_submissions",
        name_ko="첫 실력 점검",
        description_ko="서버에 검증된 퀴즈 응시를 처음 제출합니다.",
        category=AchievementCategory.QUIZ,
        tier=AchievementTier.BRONZE,
        metric=GamificationMetric.QUIZ_SUBMISSIONS,
        target_value=1,
        reward_exp=10,
        sort_order=110,
        badge=_badge("first_quiz", "첫 실력 점검 배지", "❓", BadgeRarity.COMMON),
    ),
    AchievementDefinition(
        key="first_perfect_quiz",
        series_key="perfect_quizzes",
        name_ko="완벽한 점검",
        description_ko="퀴즈에서 처음으로 만점을 받습니다.",
        category=AchievementCategory.QUIZ,
        tier=AchievementTier.SILVER,
        metric=GamificationMetric.PERFECT_QUIZZES,
        target_value=1,
        reward_exp=20,
        sort_order=120,
        badge=_badge("perfect_quiz", "완벽한 점검 배지", "💯", BadgeRarity.RARE),
    ),
    AchievementDefinition(
        key="balanced_plan_completed",
        series_key="balanced_plans_completed",
        name_ko="균형 잡힌 완주",
        description_ko="학습·복습·퀴즈 과제를 모두 포함한 계획을 완주합니다.",
        category=AchievementCategory.BALANCE,
        tier=AchievementTier.GOLD,
        metric=GamificationMetric.BALANCED_COMPLETED_PLANS,
        target_value=1,
        reward_exp=30,
        sort_order=130,
        badge=_badge("balanced_finisher", "균형 잡힌 완주 배지", "⚖️", BadgeRarity.EPIC),
    ),
)


CHALLENGE_TEMPLATE_CATALOG: tuple[ChallengeTemplate, ...] = (
    ChallengeTemplate(
        key="daily_complete_1_task",
        name_ko="오늘의 첫 과제",
        description_ko="오늘 수행 가능한 과제 1개를 완료합니다.",
        period_type=ChallengePeriodType.DAILY,
        difficulty=ChallengeDifficulty.EASY,
        metric=GamificationMetric.COMPLETED_TASKS,
        target_value=1,
        reward_exp=5,
        sort_order=10,
    ),
    ChallengeTemplate(
        key="daily_complete_2_tasks",
        name_ko="두 걸음 전진",
        description_ko="오늘 수행 가능한 서로 다른 과제 2개를 완료합니다.",
        period_type=ChallengePeriodType.DAILY,
        difficulty=ChallengeDifficulty.NORMAL,
        metric=GamificationMetric.COMPLETED_TASKS,
        target_value=2,
        reward_exp=10,
        sort_order=20,
    ),
    ChallengeTemplate(
        key="daily_complete_1_review",
        name_ko="오늘의 복습",
        description_ko="오늘 수행 가능한 복습 과제 1개를 완료합니다.",
        period_type=ChallengePeriodType.DAILY,
        difficulty=ChallengeDifficulty.EASY,
        metric=GamificationMetric.COMPLETED_REVIEW_TASKS,
        target_value=1,
        reward_exp=5,
        sort_order=30,
    ),
    ChallengeTemplate(
        key="daily_submit_1_quiz",
        name_ko="오늘의 실력 점검",
        description_ko="오늘 수행 가능한 퀴즈 1개에 응시합니다.",
        period_type=ChallengePeriodType.DAILY,
        difficulty=ChallengeDifficulty.EASY,
        metric=GamificationMetric.DISTINCT_QUIZZES,
        target_value=1,
        reward_exp=5,
        sort_order=40,
    ),
    ChallengeTemplate(
        key="daily_complete_all_tasks",
        name_ko="오늘 계획 마무리",
        description_ko="오늘 예정된 과제를 모두 완료합니다.",
        period_type=ChallengePeriodType.DAILY,
        difficulty=ChallengeDifficulty.NORMAL,
        metric=GamificationMetric.ALL_SCHEDULED_TASKS_COMPLETED,
        target_value=1,
        reward_exp=5,
        sort_order=50,
    ),
    ChallengeTemplate(
        key="weekly_complete_5_tasks",
        name_ko="주간 과제 5개",
        description_ko="이번 주 수행 가능한 서로 다른 과제 5개를 완료합니다.",
        period_type=ChallengePeriodType.WEEKLY,
        difficulty=ChallengeDifficulty.NORMAL,
        metric=GamificationMetric.COMPLETED_TASKS,
        target_value=5,
        reward_exp=15,
        sort_order=110,
    ),
    ChallengeTemplate(
        key="weekly_complete_10_tasks",
        name_ko="주간 과제 10개",
        description_ko="이번 주 수행 가능한 서로 다른 과제 10개를 완료합니다.",
        period_type=ChallengePeriodType.WEEKLY,
        difficulty=ChallengeDifficulty.CHALLENGING,
        metric=GamificationMetric.COMPLETED_TASKS,
        target_value=10,
        reward_exp=20,
        sort_order=120,
    ),
    ChallengeTemplate(
        key="weekly_study_4_days",
        name_ko="주 4일 학습",
        description_ko="이번 주 서로 다른 4일에 검증된 학습 행동을 완료합니다.",
        period_type=ChallengePeriodType.WEEKLY,
        difficulty=ChallengeDifficulty.NORMAL,
        metric=GamificationMetric.STUDY_DAYS,
        target_value=4,
        reward_exp=15,
        sort_order=130,
    ),
    ChallengeTemplate(
        key="weekly_complete_1_review",
        name_ko="주간 복습 한 번",
        description_ko="이번 주 수행 가능한 복습 과제 1개를 완료합니다.",
        period_type=ChallengePeriodType.WEEKLY,
        difficulty=ChallengeDifficulty.EASY,
        metric=GamificationMetric.COMPLETED_REVIEW_TASKS,
        target_value=1,
        reward_exp=10,
        sort_order=140,
    ),
    ChallengeTemplate(
        key="weekly_submit_1_quiz",
        name_ko="주간 실력 점검",
        description_ko="이번 주 수행 가능한 퀴즈 1개에 응시합니다.",
        period_type=ChallengePeriodType.WEEKLY,
        difficulty=ChallengeDifficulty.EASY,
        metric=GamificationMetric.DISTINCT_QUIZZES,
        target_value=1,
        reward_exp=10,
        sort_order=150,
    ),
    ChallengeTemplate(
        key="weekly_complete_1_plan",
        name_ko="이번 주 계획 완주",
        description_ko="이번 주 완료 가능한 학습계획 하나를 완주합니다.",
        period_type=ChallengePeriodType.WEEKLY,
        difficulty=ChallengeDifficulty.CHALLENGING,
        metric=GamificationMetric.COMPLETED_PLANS,
        target_value=1,
        reward_exp=15,
        sort_order=160,
    ),
)


ACHIEVEMENTS_BY_KEY = {
    definition.key: definition for definition in ACHIEVEMENT_CATALOG
}
CHALLENGE_TEMPLATES_BY_KEY = {
    template.key: template for template in CHALLENGE_TEMPLATE_CATALOG
}
